version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
        # mocha needs to be < 8.1, may be fixed but waiting for release
      - dependency-name: "mocha"
