language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    npm run test:diff || travis_terminate 1;
  fi
env:
  global:
  # S3ID
  - secure: vXP8PDm8MQhu1fTaefrX8db4cpu7OCvEn95k3iPrWVpKpscHwtQQABcskgFj8GZ2uEMnVK4X6KZmv8fPHs94z6fTBey0VJinfV1wpiCVyff83HKnjRK91K0JoAcqIWwT8oEKwxCfKKJ15aHCwtGTHsyx4VB0sy60+Kcla2W02A+MV+oriV4lPc4N+EiVTML1NcOmYdNtgi8kOORKMWLo+BGyvM9WiGi1q5eworncAhhYZnaHYRWdcD2JyZxBro9XcDNx4DGkCc8kQIg/cS57xXXdtxWBpVlf6Egnkr7yYK2InSj1/rS6VdL0YPYz0lmEk9mE/b11vstuFBrPcQHH8A1Yb9rPiyag7rx4OFmZES+CF7s6Ym/fRQiK6YQK2hAxox/4P50SMQzL5yD7QoifRs9g6f/vM9Kssspq9xvQOt+n2/lKaq4h8RJF2ZhQpqOEa6VKmP0JNt/LLDJ5qN5ztyoIiBnrcNPgkc7LgzdXbJ4zNal+44KEbCJHVmk4RpTudDindJzEj7AMmtm7/M0E92Bi7cFpgyvcPKqWbK2VrwFtYnBRlqJ/8sihIKN+AjiBfn52UF2cfirFIVg30hnv+bWnozskQAv6EigO2HlxOYqMWGxOhbKAIR2ubqRDAIb3pV+4B0UCLOj2rQM5kjC6HYpbghytfRYnC8Z40YQ632w=
  # S3KEY
  - secure: 0cnPtkyvVC9xAhW00QSJrE9pdxPWCCtCJwP1rEqFJ7uksQzrqVJFCoOxf5AzAzW15Z6Haz0RhrvD9CHOFQJHQdILD3fYoLpv88OU3Rjv2O0r0fzWzCVje7DCoEqBxJIheBHdwQB77bqSqTeelhawEdhe3Lhh98YB+S0QDE7Yjd86rQHgsEalOdRbyNOa47OHoexD3OtODsaqovCuUXzpzN6v5duLHcWWFGUq10UTEhBZ8r6RmmExTLNzlY37epGeqlkKS2LrxYWGHrHz7ikI8mFl48KsJU3vAh5oD9f9EiQbt5e7DxZtu7blbMn0I+UWfNONIiKjpO83B3lmEzXTFD+B8vGfc+byCtD0cn6UrwBdVWlgvzgjNtrjoNWEShOKndVoll34OyWBu07ChgpOVmrFGTxTZVQ7vSq9UuAPX0rfx4U1K2wwrzSCPXhfKHYnsBFsAtv16jbaop43OegbfhgsvhqjRPYc0pr0OFR0X4b32uh7Ha4o+icl58kzL9TK5O3mCPFOGApZDDC0tc7y4PuRRBNQb1c8jSn2HyuagVEs7UVB2VGrYyqyZtKjUcOrW1jajkTFK/RBmKnQVIbpAsWekqRJ2LCOQUdgYf8LlHf8Dm4ZWyNeZeOIQcJ78GXyT5P1oVdftdV+Hp+YySFqM9u0viGjh+Tq8sxiHaED0j4=
