language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    npm run test:diff || travis_terminate 1;
  fi
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 8d2e...92e1
    secure: jHxql0zjB3G6tzW0SIDmzIDRl/evH5dc2zApGVgWg4PkWUIO2PF2xjnaiZmPPcJjrmzQcVuDdLaUsGPSBRY9LzT0BHDbyaQdFsJsSjF+50uFotrYZNSAtn3K+lfjigZfo3MrOpx3M1bcNVodFi/3ItYzjYvMp73Mrk6jwpEg+v0isAAFRvkvT65Pmh64ucCRJqT4JY4PFj8v+Nzn2dbSxpd0TZahTLNHqDQZMkiuYdy1CnidhNgy4ID2wgKeNgl4DO9lY7kgh2lCK8Ljvs7G8JOjrE/i/tlVOiYa/wzKourQdRbtGLnt1YKeHRXoLYYPjV0s7JBhnhlJWk2ULeTqeqPlqGo6nR/Xjq+W3AtftCykM5vH8R9nZt+hipzl70cZ7wPmyWfUdt1oprdX81Yyk/ZlhEiZWamvbNGqhaZfdw1/5yHX3u4GhLt48dBJQjeiMd74Ep5ywaWPxzEFmyg/yRGhnNemfD0L1/p5/x1jzfFudaHIuGBHNLOhQbQ5+ZFi+UTAJTkvIsNeqVcVbkGPTCOme9XuBmJj2rWPCVDQs2udc1vb5ij1imHY8Z/dYIGcWZCvqtPTewxtQaudujelaW/K4wVY4ipGxMDCxIewivKaPGHt5upVsLLPd7GkW4t4WFZg0pfC9DsTXiQnyin0DrJGXoyO7ZUWwyaGBjpa+iU=
  on:
    tags: true
    repo: BrightspaceUI/visual-diff
    all_branches: true
env:
  global:
  # VISUAL_DIFF_S3_ID
  - secure: R1rn6izc5JY+Bq7HSZOzd67Ves6Pl+ojiQh7FfPnDcyYW1bRqBfV+GLJJMsmP2dmtzhanfakIHoitiA6+FUJmQEC6bda1gpHZkDjxoi/hmSOlysmNH7/ITMXA6ZuZXZ96QgMc7sUhYbQQ1vWqrEZ3T/Gw6tab/zBG4Og/48zhSWJNbg9AClqXB1xA/HeF+yF6iWFyBNAJmdkVihncDPEzt7eWGIkKKghmefRh9LY3d1wT6Rz1COE1G4XRrN74kIXURXiZtejsuGEXe9qDzMcNATEvPOd4mcqgITS8z0EGl/ahCGkUFzMTV8wUD3sulu1zwsa0xAjCjkgpNlOCpIQZ+e5pTFbyQWxJqRGDzgPfZsiPjCS5ckZefZxP6E3exVl04fBjjlliUUfYhasQyuDQxoDgA60nXL3x9CGrEsCGLZIwWhZV4H2h+P9SJR16BdLY+ehAbWaBgIajRYrNNPd84K8nVad1cgp5XzJtfDgWY/UT49BN11isNef+3NSH7527G/SKVyh3vp8F2w9nZwSJ2d+eJ6IlbfgL/PLUXjGGyzOi+biF/BqbwveJnCkHHphaCuwlg+eDGPL/5Mi1IE8qzK7bwXGwPPk86KEPTEthsnOEDSl8UShs+SiLQFinRGbFXlDKKp8bLqYYOxN3i8VaneWAnj2gE62WLvmBp3GCKE=
  # VISUAL_DIFF_S3_SECRET
  - secure: bQNi80DOGZYEHuI23qtDbYxbSaseOouhut+YZnMebsENDXrwnP9x4NFhBFhLuZHwH/UzViC4rWkJ5pZJLiKgw3yrchSGBIj/zY+CFfDbzyaDI+za7l3viY1UuKKnFr6OMq4GCow+D9Fw8Fi+isZIJuZQTKFv5bXyg5FPvinJWB6sAbHOqxwdIo2wvEbHZ3ZP/k6RwoL/Jo5lKUvXOGK+8+3SnbSNYfNMlqGHjYhhaLF4EX57aWocUmweh6wuY4HeHCfMN/emHKu/7U2ZTxVn/QTp/trr626pK2O7c0+1h2NCNrXmzw7fpxrmAUqL/EmqpYqkoXWXiAyD+vWA/IRFo3BPEi3yoZT0dH+BhPGNDvzGjBXjTv1X0QgYwTF+a+yTfy27dWTlodjTzcgszWa0/Ih2TFflwbmcCFG3/jaUA2qS4wCfdsho8CXekpZpZglu4dcIOJSKg4wJc23IUXtGoR8d7BXOkuztMTW/2t8u7tQBrHif5aAUrtGRv6I5xAJ2BXAWe2RQKr5ElZg4QLf8AQFOeqTyKZnkRC+nWWOzAJQAoN+SzCBY1WcJz04FKzl+3yajDn5TujLQaOirpCbBRoSO2nU5MZnQaazSrV2ojSEKOpk20rE04EPwRe8BeyPf+eECteMEg1RtEOKGcdkZ8arJM3P8gVGuPkQHiAAuZQw=
  # GITHUB_RELEASE_TOKEN
  - secure: L8fyj8yBdxJSUYP03uEahfdaaSSrWIcUm4M59YuatZOxr7LcAyAIRiHeau6XmcZbvl21xhVqr8ssn4qUbiQgz5VBBJCCHdbKyVkZZTxI8UhB6WXZ7PpGpy1qEJY9nI2bBVDlNCOdThyuxN5G8vUxY9HwYjW5xq+eJ3AkjUxyXjk0qEbsSNAnBOKHY/zhGh3C4xaytuaXJR+mr270KE94lDDsEEZ+paBfAwoCrlYKgodsTeRWd6re0N1wr+d8CcSc1WspW4lYrWl0njl3tWRfhOGorNbP8vxAWeLwGmlISmg01uitZZVCWgi008D0Rr3wrdlBUu8aXeZkTxriv/el3dyUTfDnIdc2PzDkArlonWny1HRtcf0RYVOaSKNTeK1z5xz2zvEGzZQsifh2fo9ky5AfPlohOSP5pu5U8l6+GVU2YR9lRSZ+/DhdrFyiAfRLUyRwbkBCG3bcXEzL+cB0UeWdrFTgJPddVwiH0tbQg3f9ccR3fz2aUqcdGFc8XkZsiOnG+fq64DA6NO0yi8b37/eSqXw3ZtcZE1m7S+puQckTzyJnmIT2aN9iAtE/T4m6eiJY0aGijYBKOmKNcky+cVm8/Qj8zh3Jl45Gs/jAgP+yjiUFEUyQH5wW8ZQossqrXNlHcTIa2z+ez76RcRXhhNG8Irts4DPjUOQZqaWsfmg=
